# renovate: datasource=github-releases packageName=caddyserver/caddy
ARG CADDY_VERSION=2.11.1

FROM caddy:${CADDY_VERSION}-builder AS builder

# renovate: datasource=github-tags packageName=caddy-dns/cloudflare
ARG CADDY_DNS_CLOUDFLARE_VERSION=0.2.3
# renovate: datasource=github-tags packageName=greenpau/caddy-security
ARG CADDY_SECURITY_VERSION=1.1.32

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare@v${CADDY_DNS_CLOUDFLARE_VERSION} \
    --with github.com/greenpau/caddy-security@v${CADDY_SECURITY_VERSION} \
    --with github.com/WeidiDeng/caddy-cloudflare-ip

FROM gcr.io/distroless/static-debian13:nonroot@sha256:0376b514983f02c630de9ed8abadd33968ddb778f9f383412a12babe639cbaaa AS final

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
