# renovate: datasource=github-releases packageName=caddyserver/caddy
ARG CADDY_VERSION=2.11.2

FROM caddy:${CADDY_VERSION}-builder AS builder

# renovate: datasource=github-tags packageName=caddy-dns/cloudflare
ARG CADDY_DNS_CLOUDFLARE_VERSION=0.2.3
# renovate: datasource=github-tags packageName=greenpau/caddy-security
ARG CADDY_SECURITY_VERSION=1.1.43

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare@v${CADDY_DNS_CLOUDFLARE_VERSION} \
    --with github.com/greenpau/caddy-security@v${CADDY_SECURITY_VERSION} \
    --with github.com/WeidiDeng/caddy-cloudflare-ip

FROM gcr.io/distroless/static-debian13:nonroot@sha256:963fa6c544fe5ce420f1f54fb88b6fb01479f054c8056d0f74cc2c6000df5240 AS final

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
