# renovate: datasource=github-releases packageName=caddyserver/caddy
ARG CADDY_VERSION=2.11.1

FROM caddy:${CADDY_VERSION}-builder AS builder

# renovate: datasource=github-tags packageName=caddy-dns/cloudflare
ARG CADDY_DNS_CLOUDFLARE_VERSION=0.2.3
# renovate: datasource=github-tags packageName=greenpau/caddy-security
ARG CADDY_SECURITY_VERSION=1.1.32

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare@v${CADDY_DNS_CLOUDFLARE_VERSION} \
    --with github.com/greenpau/caddy-security@v${CADDY_SECURITY_VERSION} \
    --with github.com/WeidiDeng/caddy-cloudflare-ip

FROM gcr.io/distroless/static-debian13:nonroot@sha256:f512d819b8f109f2375e8b51d8cfd8aafe81034bc3e319740128b7d7f70d5036 AS final

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

CMD ["caddy", "run", "--config", "/etc/caddy/Caddyfile", "--adapter", "caddyfile"]
