---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR - Lint Renovate

on:
  pull_request:
    paths:
      - .renovaterc.json5
      - .renovate/**.json5

permissions:
  contents: read

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      changed-renovate-files: ${{ steps.changed-renovate-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Get all changed Renovate config files
        id: changed-renovate-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            .renovaterc.json5
            .renovate/**.json5
          matrix: true

  lint:
    name: Lint Renovate Config
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:43.271.3@sha256:6f287995d37359e0d141a112ec5f661d29936d48c22b0736c3c887b2de81f309
      options: --user 0
    needs:
      - prepare
    strategy:
      matrix:
        files: ${{ fromJSON(needs.prepare.outputs.changed-renovate-files) }}
      fail-fast: false
      max-parallel: 4
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Validate Renovate Configuration
        run: |
          renovate-config-validator --strict ${{ matrix.files }}
        shell: bash
